package main

import (
	"github.com/terraform-linters/tflint-plugin-sdk/plugin"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/wata727/tflint-ruleset-awscx/rules"
)

func main() {
	plugin.Serve(&plugin.ServeOpts{
		RuleSet: &tflint.BuiltinRuleSet{
			Name:    "awscx",
			Version: "0.1.0",
			Rules: []tflint.Rule{
				rules.NewAwsAPIGatewayDeploymentDeprecatedStageManagementRule(),
				rules.NewAwsAutoscalingGroupInvalidMaxInstanceLifetimeRule(),
				rules.NewAwsCloudFrontDistributionMinimumProtocolVersionDefaultCertificateRule(),
				rules.NewAwsCloudWatchLogGroupDeliveryRetentionInDaysRule(),
				rules.NewAwsDBInstanceBlueGreenUpdateWithoutBackupRetentionRule(),
				rules.NewAwsDBInstanceDatabaseInsightsAdvancedRequirementsRule(),
				rules.NewAwsDBInstanceDedicatedLogVolumeNonIO1IO2Rule(),
				rules.NewAwsDBInstanceEnhancedMonitoringRoleRequirementsRule(),
				rules.NewAwsDBInstanceManageMasterUserPasswordConflictRule(),
				rules.NewAwsDBInstancePerformanceInsightsArgumentsWithoutEnabledRule(),
				rules.NewAwsDBInstanceMissingIOPSRule(),
				rules.NewAwsDBInstanceStorageThroughputNonGP3Rule(),
				rules.NewAwsDynamoDBTableInvalidStreamViewTypeRule(),
				rules.NewAwsEBSVolumeMissingIOPSRule(),
				rules.NewAwsEBSVolumeThroughputNonGP3Rule(),
				rules.NewAwsEIPInstanceNetworkInterfaceConflictRule(),
				rules.NewAwsECSServiceDaemonFargateLaunchTypeRule(),
				rules.NewAwsECSServiceDaemonUnsupportedDeploymentControllerRule(),
				rules.NewAwsECSServiceDeploymentMaximumPercentDaemonRule(),
				rules.NewAwsECSServiceHealthCheckGracePeriodWithoutLoadBalancerRule(),
				rules.NewAwsEKSAddonDeprecatedResolveConflictsRule(),
				rules.NewAwsEFSFileSystemMissingProvisionedThroughputRule(),
				rules.NewAwsEFSFileSystemKMSKeyWithoutEncryptedRule(),
				rules.NewAwsEFSFileSystemProvisionedThroughputNonProvisionedRule(),
				rules.NewAwsInstanceDeprecatedNetworkInterfaceRule(),
				rules.NewAwsLBListenerALPNPolicyNonTLSRule(),
				rules.NewAwsLBListenerMissingCertificateARNRule(),
				rules.NewAwsLBListenerMutualAuthenticationVerifyRequirementsRule(),
				rules.NewAwsLBListenerMissingSSLPolicyRule(),
				rules.NewAwsLBTargetGroupMatcherNonHTTPHealthCheckRule(),
				rules.NewAwsLBTargetGroupLambdaTopLevelAttributesRule(),
				rules.NewAwsLBTargetGroupProtocolVersionNonHTTPRule(),
				rules.NewAwsLambdaFunctionZipRequiredAttributesRule(),
				rules.NewAwsLaunchTemplateDeprecatedElasticInferenceAcceleratorRule(),
				rules.NewAwsLaunchTemplateDeprecatedElasticGPUSpecificationsRule(),
				rules.NewAwsInstanceIMDSv2OptionalTokensRule(),
				rules.NewAwsLaunchTemplateIMDSv2OptionalTokensRule(),
				rules.NewAwsS3BucketDeprecatedAccelerationStatusRule(),
				rules.NewAwsS3BucketDeprecatedACLRule(),
				rules.NewAwsS3BucketConfigurationExpectedBucketOwnerDeprecatedRule(),
				rules.NewAwsS3BucketDeprecatedGrantRule(),
				rules.NewAwsS3BucketDeprecatedLifecycleRule(),
				rules.NewAwsS3BucketDeprecatedLoggingRule(),
				rules.NewAwsS3BucketDeprecatedObjectLockConfigurationRule(),
				rules.NewAwsS3BucketDeprecatedPolicyRule(),
				rules.NewAwsS3BucketDeprecatedRequestPayerRule(),
				rules.NewAwsS3BucketDeprecatedReplicationConfigurationRule(),
				rules.NewAwsS3BucketDeprecatedServerSideEncryptionConfigurationRule(),
				rules.NewAwsS3BucketDeprecatedVersioningRule(),
				rules.NewAwsS3BucketDeprecatedWebsiteRule(),
				rules.NewAwsSNSTopicFIFOAttributesWithoutFIFOTopicRule(),
				rules.NewAwsSNSTopicFIFONameSuffixRule(),
				rules.NewAwsSecurityGroupAllProtocolNonzeroPortsRule(),
				rules.NewAwsSecurityGroupInvalidProtocolRule(),
				rules.NewAwsSFNStateMachineLogDestinationMissingWildcardRule(),
				rules.NewAwsSQSQueuePolicyMissingCurrentVersionRule(),
				rules.NewAwsSQSQueueFIFONameSuffixRule(),
			},
		},
	})
}
